spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/
    username: root
    password: belegmaschine
    driver-class-name: org.mariadb.jdbc.Driver
  #  jpa.hibernate.ddl-auto: create-drop
  flyway:
    defaultSchema: bm
    enables: true
    validate-on-migrate: true
    schemas: bm
    locations: classpath:db/migration
    cleanOnValidationError: true